### ISSUE TITLE
Add support for `Collectable` events.

### ISSUE THREAD

**Issue by jtourkos** [drips-network/subgraph#7]
We support `Collected`, but it would be great also to support `Collectable` events as well.

**Comment by gh0stwheel** [comment]
Hey @jtourkos -- I've added basic support for this through a CollectableEvent type:

https://github.com/radicle-dev/drips-subgraph/blob/fb1a3430c95d2d884f53967f9eb40238c5ad459e/schema.graphql#L133

Do you think that this is enough, or are there other types or fields you would like to see added? One idea that comes to mind is that it might be nice to add `amtCollectable` to the UserAssetConfig type, similar to how we have `amtCollected`. What do you think?

**Comment by jtourkos** [comment]
Thanks, @gh0stwheel! 
I think we're OK for now like this; no need for further additions.
(the SDK also provides methods for retrieving the _collectable_ amount)
