### ISSUE TITLE
Add support for `Splittable` events

### ISSUE THREAD

**Issue by jtourkos** [drips-network/subgraph#8]
After [this PR](https://github.com/radicle-dev/drips-contracts/issues/243) is merged, could we add support for the new `Splittable` events?

**Comment by gh0stwheel** [comment]
@jtourkos -- see Igor's most recent comment here: https://github.com/radicle-dev/drips-contracts/issues/243

Do you think that the approach he proposes (specifically, *not* adding Splittable events), would meet your needs based on the current subgraph design in terms of being able to distinguish Splits from Gives?

I'm happy to try to add some additional calculated fields to the entity types if that would be helpful...
